# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# XDC: new/mc6800_controller.xdc

# Block Designs: bd/arty_eth_000/arty_eth_000.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000 || ORIG_REF_NAME==arty_eth_000} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_clk_wiz_0_1/arty_eth_000_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_clk_wiz_0_1 || ORIG_REF_NAME==arty_eth_000_clk_wiz_0_1} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_mig_7series_0_0/arty_eth_000_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_mig_7series_0_0 || ORIG_REF_NAME==arty_eth_000_mig_7series_0_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_microblaze_0_0/arty_eth_000_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_microblaze_0_0 || ORIG_REF_NAME==arty_eth_000_microblaze_0_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_microblaze_0_axi_periph_0/arty_eth_000_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_microblaze_0_axi_periph_0 || ORIG_REF_NAME==arty_eth_000_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_microblaze_0_axi_intc_0/arty_eth_000_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_microblaze_0_axi_intc_0 || ORIG_REF_NAME==arty_eth_000_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_microblaze_0_xlconcat_0/arty_eth_000_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_microblaze_0_xlconcat_0 || ORIG_REF_NAME==arty_eth_000_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_mdm_1_0/arty_eth_000_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_mdm_1_0 || ORIG_REF_NAME==arty_eth_000_mdm_1_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_rst_mig_7series_0_83M_0/arty_eth_000_rst_mig_7series_0_83M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==arty_eth_000_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_axi_uartlite_0_0/arty_eth_000_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_axi_uartlite_0_0 || ORIG_REF_NAME==arty_eth_000_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_axi_ethernetlite_0_0/arty_eth_000_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_axi_ethernetlite_0_0 || ORIG_REF_NAME==arty_eth_000_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_axi_timer_0_0/arty_eth_000_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_axi_timer_0_0 || ORIG_REF_NAME==arty_eth_000_axi_timer_0_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_axi_smc_0/arty_eth_000_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_axi_smc_0 || ORIG_REF_NAME==arty_eth_000_axi_smc_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_xbar_0/arty_eth_000_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_xbar_0 || ORIG_REF_NAME==arty_eth_000_xbar_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_dlmb_v10_0/arty_eth_000_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_dlmb_v10_0 || ORIG_REF_NAME==arty_eth_000_dlmb_v10_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_ilmb_v10_0/arty_eth_000_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_ilmb_v10_0 || ORIG_REF_NAME==arty_eth_000_ilmb_v10_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_dlmb_bram_if_cntlr_0/arty_eth_000_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==arty_eth_000_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_ilmb_bram_if_cntlr_0/arty_eth_000_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==arty_eth_000_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_lmb_bram_0/arty_eth_000_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_lmb_bram_0 || ORIG_REF_NAME==arty_eth_000_lmb_bram_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_mc6800_controller_0_0/arty_eth_000_mc6800_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_mc6800_controller_0_0 || ORIG_REF_NAME==arty_eth_000_mc6800_controller_0_0} -quiet] -quiet

# IP: bd/arty_eth_000/ip/arty_eth_000_mc6800_controller_1_0/arty_eth_000_mc6800_controller_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_eth_000_mc6800_controller_1_0 || ORIG_REF_NAME==arty_eth_000_mc6800_controller_1_0} -quiet] -quiet

# XDC: bd/arty_eth_000/arty_eth_000_ooc.xdc
