# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/phaz/vivado_projects/arty_eth_000/arty_eth_000.srcs/sources_1/bd/arty_eth_000/ip/arty_eth_000_lmb_bram_0/arty_eth_000_lmb_bram_0.xci
# IP: The module: 'arty_eth_000_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/phaz/vivado_projects/arty_eth_000/arty_eth_000.srcs/sources_1/bd/arty_eth_000/ip/arty_eth_000_lmb_bram_0/arty_eth_000_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_eth_000_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/phaz/vivado_projects/arty_eth_000/arty_eth_000.srcs/sources_1/bd/arty_eth_000/ip/arty_eth_000_lmb_bram_0/arty_eth_000_lmb_bram_0.xci
# IP: The module: 'arty_eth_000_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/phaz/vivado_projects/arty_eth_000/arty_eth_000.srcs/sources_1/bd/arty_eth_000/ip/arty_eth_000_lmb_bram_0/arty_eth_000_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_eth_000_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
